name: Build MacOS Release Archive
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - cmake

jobs:
  build:

    runs-on: macos-latest

    steps:
      # This action checks-out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          echo brew install pkg-config pcsc-lite check gengetopt help2man
          brew install pkg-config pcsc-lite check gengetopt help2man
      - name: Build macos executables archive
        run: |
          ./macos/make_pkg.sh 2.1.0 2 /usr/local
          mkdir macos/artifact
          mv macos/yubico-piv-tool*.zip macos/artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubico-piv-tool-mac
          path: macos/artifact