name: CMake Build Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        run: |
          echo "mkdir cmake_build; cd cmake_build"
          mkdir cmake_build; cd cmake_build

          echo cmake -A Win32 -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON -DBACKEND=winscard ..
          cmake -A Win32 -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON -DBACKEND=winscard ..

          echo cmake --build . -v
          cmake --build . -v

          echo "yubico-piv-tool.exe"
          cd tool/Debug
          yubico-piv-tool.exe --version

