name: Build Static Linking
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - cmake

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # This action checks-out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          echo sudo apt install check gengetopt help2man
          sudo apt install check gengetopt help2man

          echo sudo apt install libsystemd-dev libudev-dev flex
          sudo apt install libsystemd-dev libudev-dev flex
      - name: install pcsc from source
        run: |
          cd $HOME
          echo git clone https://salsa.debian.org/rousseau/PCSC.git
          git clone https://salsa.debian.org/rousseau/PCSC.git

          echo cd PCSC
          cd PCSC

          echo ./bootstrap
          ./bootstrap

          echo ./configure --enable-static
          ./configure --enable-static

          echo make
          make

          echo sudo make install
          sudo make install

      - name: run cmake
        run: |

          echo export PKG_CONFIG_PATH=$HOME/PCSC/src/.libs:$PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=$HOME/PCSC/src/.libs:$PKG_CONFIG_PATH

          echo mkdir cmake_build
          mkdir cmake_build

          echo cd cmake_build
          cd cmake_build

          echo cmake .. -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON -DRELEASE_BUILD=1 -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static"
          cmake .. -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON -DRELEASE_BUILD=1 -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static"

          echo make
          make

          echo make test
          make test

          echo ldd tool/yubico-piv-tool
          ldd tool/yubico-piv-tool

          echo ldd tool/yubico-piv-tool_static
          ldd tool/yubico-piv-tool_static